config/routes.rb
Rails.application.routes.draw do
  resources :hash_tag and
  resources :users do
    resources :tweets
  end
  get 'welcome/index'

  root 'welcome#index'

  resources :follows, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true

end

app/models/hash_tag.rb
class HashTag < ApplicationRecord

  validates :name,
            uniqueness: true,
            presence: true,
            length: {minimum: 2, maximum: 42}

  has_and_belongs_to_many :tweets
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  validates :body,
            presence: true,
            length: {minimum: 2, maximum: 142}

  has_and_belongs_to_many :hash_tags

  after_save :parse_hash_tags

  def parse_hash_tags
    hash_tags_array = []
    self.body.scan(/#\w+/).flatten.each do |hash_tag|
      hash_tags_array.push(HashTag.where(name: hash_tag).first_or_create)
    end
    self.hash_tags = hash_tags_array
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_many :follows, dependent: :destroy
  has_many :active_relationships, class_name: "Follow",
           foreign_key: "follower_id",
           dependent: :destroy
  has_many :passive_relationships, class_name:  "Follow",
           foreign_key: "followed_id",
           dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :tweets, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  has_secure_password
  before_save {email.downcase!}
  validates :name,
            presence: true,
            uniqueness: true,
            length: {minimum: 3, maximum: 50}

  validates :email,
            presence: true,
            uniqueness: true,
            length: {minimum: 3, maximum: 50},
            format: {with: EMAIL_REGEX}

  validates :picture,
            allow_nil: true,
            url: true,
            length: {maximum: 255}

  validates :password,
            presence: true,
            confirmation: true,
            length: {minimum: 8, maximum: 255}

  # Follows a user.
  def follow(other_user)
    following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  # POST /follows
  def create
    @user = User.find(params[:user_id])
    @following_user = User.find(params[:following_user_id])

    respond_to do |format|
      if @following_user.follow(@user)
        format.html {redirect_to user_path(@user), notice: 'Successfully followed.'}
      else
        format.html {redirect_to user_path(@user), error: 'Something went wrong.'}
      end
    end
  end

  # DELETE /follows/1
  def destroy
    @user = User.find(params[:user_id])
    @following_user = User.find(params[:following_user_id])

    respond_to do |format|
      if @following_user.unfollow(@user)
        format.html {redirect_to user_path(@user), notice: 'Successfully unfollowed.'}
      else
        format.html {redirect_to user_path(@user), error: 'Something went wrong.'}
      end
    end
  end

end

app/controllers/hash_tag_controller.rb
class HashTagController < ApplicationController


  # GET /hash_tag/1
  def show
    @tweets = Tweet.all
    @hash_tags = HashTag.all
    @hash_tag = HashTag.find(params[:id])
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  def index
    @user_tweets = User.find(params[:user_id]).tweets.order(:created_at)
    @user =  User.find(params[:user_id])
    @tweets = Tweet.all
    @hash_tags = HashTag.all
  end

  # GET /tweets/1
  def show
  end

  # GET /tweets/new
  def new
    @tweets = Tweet.all
    @tweet = Tweet.new
    @hash_tags = HashTag.all
  end

  # GET /tweets/1/edit
  def edit
    @tweets = Tweet.all
    @hash_tags = HashTag.all
  end

  # POST /tweets
  def create
    @user = User.find(params[:user_id])
    @tweet = @user.tweets.create(tweet_params)
    @hash_tags = HashTag.all
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to user_tweets_path(@user), notice: 'Tweet was successfully created.' }
      else
        format.html { redirect_to user_tweets_path(@user), error: 'Something went wrong' }
      end
    end
  end

  # PATCH/PUT /tweets/1
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
      else
        format.html { redirect_to user_tweets_path(@user), error: 'Something went wrong' }
      end
    end
  end

  # DELETE /tweets/1
  def destroy
    @user = User.find(params[:user_id])
    @tweet = @user.tweets.find(params[:id])
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to user_tweets_path(@user), notice: 'Tweet was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:body, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
    @tweets = Tweet.all
    @hash_tags = HashTag.all
  end

  # GET /users/1
  def show
    @tweets = Tweet.all
    @users = User.all
    @followers_tweets = Array.new
    @hash_tags = HashTag.all
    @user.followers.each do |follow|
      follow.tweets.each do |new_tweets|
        @followers_tweets.push(new_tweets)
      end
    end

  end

  # GET /users/new
  def new
    @user = User.new
    @tweets = Tweet.all
    @hash_tags = HashTag.all
  end

  # GET /users/1/edit
  def edit
    @tweets = Tweet.all
    @hash_tags = HashTag.all
  end

  # POST /users
  def create
    @user = User.new(user_params)
    @tweets = Tweet.all
    @hash_tags = HashTag.all
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    @tweets = Tweet.all
    @hash_tags = HashTag.all
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @tweets = Tweet.all
    @hash_tags = HashTag.all
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :picture)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @tweets = Tweet.all
    @hash_tags = HashTag.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def button_text
    if controller.action_name == "new" || controller.action_name == "create"
      return "Create User"
    elsif controller.action_name == "edit" || controller.action_name == "update"
      return "Update User"
    else
      return controller.action_name
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/hash_tag/show.html.erb
<div class="col-9">
  <div class="row bg-white">
    <div class="col-12 p-3">
      <% if @hash_tag.tweets.count > 0 %>
        <% @hash_tag.tweets.each do |tweet| %>
          <% tweet.hash_tags.each do |hashtag| %>
            <% tweet.body.sub! hashtag.name, link_to( hashtag.name,hash_tag_path(hashtag), :class => "text-info") %>
          <% end %>
          <div class="card mb-3">
            <div class="card-body">
              <%= simple_format(tweet.body, :class => "mb-0") %>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>You have no tweets!</p>
      <% end %>
      <%= link_to 'Back', :back, :class => "btn btn-outline-secondary mt-2" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter Like</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script defer src="https://use.fontawesome.com/releases/v5.7.0/js/all.js" integrity="sha384-qD/MNBVMm3hVYCbRTSOW130+CWeRIKbpot9/gR1BHkd7sIct4QKhT1hOPd+2hO8K" crossorigin="anonymous"></script>
</head>

<body class="bg-light">


<nav class="navbar navbar-expand-lg navbar-dark bg-info">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">
      <li class="nav-item">
        <%= link_to "Twitter", root_path , :class => "navbar-brand" %>
      </li>
    </ul>
  </div>
</nav>

<div class="container pt-3">
  <div class="row">
    <%= yield %>
    <div class="col-3">
      <div class="bg-white p-3">
        <div class="row border-bottom">
          <div class="col">
            <h5>Last tweets</h5>
          </div>
        </div>

        <% Tweet.order('created_at DESC').take(4).each do |tweet| %>
          <% tweet.hash_tags.each do |hashtag| %>
            <% tweet.body.sub! hashtag.name, link_to( hashtag.name,hash_tag_path(hashtag), :class => "text-info") %>
          <% end %>
          <div class="row border-bottom">
            <div class="col pt-1">
              <b><%= link_to(tweet.user.name, user_path(tweet.user), :class => "")  %></b>
              <p><%= simple_format(tweet.body) %></p>
            </div>
          </div>
        <% end %>
      </div>

      <div class="bg-white p-3 mt-3">
        <div class="row">
          <div class="col">
            <div class="row border-bottom">
              <div class="col">
                <h5>Popular Hashtag</h5>
              </div>
            </div>

            <% @hash_tags.all.each do |hashtag| %>
              <div class="row border-bottom">
                <div class="col pt-1">
                  <%= link_to( hashtag.name,hash_tag_path(hashtag), :class => "text-info")  %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: [@user, @user.tweets.build], local: true) do |form| %>
  <div class="form-group">
    <%= form.text_area :body, :class => "form-control" %>
  </div>
  <div class="form-group">
    <p class="text-right"><%= form.submit :class => "btn btn-info btn-sm" %></p>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<% tweet.hash_tags.each do |hashtag| %>
  <% tweet.body.sub! hashtag.name, link_to( hashtag.name,hash_tag_path(hashtag), :class => "text-info") %>
<% end %>

<div class="card mb-3">
  <div class="card-body">
    <%= simple_format(tweet.body, :class=>"mb-0") %>

    <p class="text-right mb-0 font-weight-bold"><%= link_to(tweet.user.name, user_path(tweet.user), :class => "") %></p>

    <!--      <p class="text-right mb-0"><%#= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, [tweet.user, tweet], method: :delete, data: {confirm: 'Are you sure ?'}, class: "btn btn-info btn-sm" %></p>-->

  </div>
</div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<div class="col-9">
  <div class="row bg-white">
    <div class="col-12 p-3">
      <% if notice %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <h5 class="text-center">My Tweets</h5>

      <div class="col-12">
        <%= render 'tweets/form' %>
      </div>


      <% if @user_tweets.count > 0 %>
        <% @user_tweets.each do |tweet| %>
          <% tweet.hash_tags.each do |hashtag| %>
            <% tweet.body.sub! hashtag.name, link_to( hashtag.name,hash_tag_path(hashtag), :class => "text-info") %>
          <% end %>

          <div class="card mb-3">
            <div class="card-body">
              <%= simple_format(tweet.body, :class => "mb-0") %>
              <p class="text-right mb-0"><%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, [tweet.user, tweet], method: :delete, data: {confirm: 'Are you sure ?'}, class: "btn btn-info btn-sm" %></p>
            </div>
          </div>
        <% end %>

      <% else %>

        <p>You have no tweets!</p>
      <% end %>
      <%= link_to 'Back', @user, :class => "btn btn-outline-secondary mt-2" %>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', :back %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @tweet.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>

  <div class="form-group">
    <%= form.label :name %>

    <% if user.errors.include?(:name)
         bootstrapclass = "is-invalid"
       else
         bootstrapclass = ""
       end
    %>

    <%= form.text_field :name, :class => "form-control " + bootstrapclass, :placeholder => :name %>

    <% if user.errors.include?(:name) %>
      <% user.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :email %>

    <% if user.errors.include?(:email)
         bootstrapclass = "is-invalid"
       else
         bootstrapclass = ""
       end
    %>

    <%= form.text_field :email, :class => "form-control " + bootstrapclass, :placeholder => :email %>

    <% if user.errors.include?(:email) %>
      <% user.errors.full_messages_for(:email).each do |message| %>
        <div class="invalid-feedback">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :picture %>

    <% if user.errors.include?(:picture)
         bootstrapclass = "is-invalid"
       else
         bootstrapclass = ""
       end
    %>

    <%= form.url_field :picture, :class => "form-control " + bootstrapclass, :placeholder => :picture %>

    <% if user.errors.include?(:picture) %>
      <% user.errors.full_messages_for(:picture).each do |message| %>
        <div class="invalid-feedback">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :password %>

    <% if user.errors.include?(:password)
         bootstrapclass = "is-invalid"
       else
         bootstrapclass = ""
       end
    %>

    <%= form.password_field :password, :class => "form-control " + bootstrapclass, :placeholder => :password %>

    <% if user.errors.include?(:password) %>
      <% user.errors.full_messages_for(:password).each do |message| %>
        <div class="invalid-feedback">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>

    <% if user.errors.include?(:password_confirmation)
         bootstrapclass = "is-invalid"
       end
    %>

    <%= form.password_field :password_confirmation, :class => "form-control " + bootstrapclass, :placeholder => :password_confirmation %>

    <% if user.errors.include?(:password_confirmation) %>
      <% user.errors.full_messages_for(:password_confirmation).each do |message| %>
        <div class="invalid-feedback">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="row">
    <div class="col-6">
      <%= link_to 'Cancel', users_path, :class => "btn btn-outline-secondary" %>
    </div>
    <div class="col-6 text-right">
      <div class="form-group">
        <%= form.submit button_text, :class => "btn btn-info" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="col-9 p-0">
  <h5>Editing User</h5>
</div>
<div class="col-9">
  <div class="row bg-white">
    <div class="col-12 p-3">
      <%= render 'form', user: @user %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!--<div class="alert" id="notice"><%#= notice %></div>-->
<div class="col-9 p-0 mb-1">
  <div class="row">
    <div class="col-auto p-0">
      <h5>Users</h5>
    </div>
    <div class="col text-right">
      <%= link_to '<i class="fas fa-user-plus"></i>'.html_safe, new_user_path, :class => "btn btn-sm btn-outline-info" %>
    </div>
  </div>
</div>
<div class="col-9 p-0">
  <div class="row">
    <% @users.each do |user| %>
      <div class="col-4">
        <div class="card">
          <img  class="card-img-top" src="<%= user.picture %>" alt="">
          <div class="card-body">
            <h5><%= user.name %></h5>
            <p class="mb-0"><%= user.email %></p>
            <small>Followers : <b><%= user.following.count %></b></small>
            <div class="text-right">
              <%= link_to 'Show', user, :class => "btn btn-outline-info" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="col-9 p-0">
  <h5>New User</h5>
</div>
<div class="col-9">
  <div class="row bg-white">
    <div class="col-12 p-3">
      <%= render 'form', user: @user %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="col-9">
  <% if notice %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
  <%# if error %>
  <!--    <div class="alert alert-danger alert-dismissible fade show" role="alert">-->
  <%#= error %>
  <!--      <button type="button" class="close" data-dismiss="alert" aria-label="Close">-->
  <!--        <span aria-hidden="true">&times;</span>-->
  <!--      </button>-->
  <!--    </div>-->
  <%# end %>
  <div class="row">
    <div class="col-12 p-0 mb-3">
      <div class="col-2">
        <img src="<%= @user.picture %>" alt="" class="img-fluid rounded ">
      </div>
      <h5><%= @user.name %></h5>
      <h6 class="text-secondary"><%= @user.email %></h6>
      <small class="">Followers : <b><%= @user.following.count %></b></small>
      <small class="">Follows : <b><%= @user.followers.count %></b></small>
      <div class="text-right">
        <%= link_to '<i class="fas fa-user-edit"></i>'.html_safe, edit_user_path(@user), :class => "btn btn-outline-secondary" %>
        <br>
        <%= link_to 'My Tweets', user_tweets_path(@user), :class => 'btn btn-sm btn-info mt-2' %>
      </div>
    </div>
  </div>

  <div class="row bg-white">
    <div class="col-12 p-3">
      <h5 class="text-center">Followers Tweets</h5>
      <% if @followers_tweets.count > 0 %>
        <%= render @followers_tweets %>
      <% else %>
        <p>Your follows have no tweets!</p>
      <% end %>
      <%= link_to 'Back', users_path, :class => "btn btn-outline-secondary mt-2" %>
    </div>
  </div>
  <div class="row bg-white">
    <div class="col-12 p-3">
      <h5>Follows</h5>
      <% @users.each do |user| %>
        <% if user.id != @user.id %>
          <div class="row">
            <div class="col-6 d-flex align-items-center">
              <%= link_to user.name, user %>
            </div>
            <div class="col-6 d-flex align-items-center justify-content-end">
              <% if user.following?(@user) %>
                <%= form_tag({controller: "follows", action: "destroy"}, method: "delete") do %>
                  <input type="hidden" name="user_id" value="<%= @user.id %>">
                  <input type="hidden" name="following_user_id" value="<%= user.id %>">
                  <input type="submit" value="Unfollow" class="btn btn-sm btn-outline-secondary mt-0">
                <% end %>
              <% else %>
                <%= form_tag(controller: "follows", action: "create") do %>
                  <input type="hidden" name="user_id" value="<%= @user.id %>">
                  <input type="hidden" name="following_user_id" value="<%= user.id %>">
                  <input type="submit" value="Follow" class="btn btn-sm btn-outline-secondary mt-0">
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="col-9 p-0 bg-white p-3">
  <h1>Twitter Light</h1>
  <p>Welcome to the Ruby Project !</p>
  <a class="btn btn-outline-info" href="/users/">Users Listing !</a>
</div>